#################################################################################
# Copyright (c) 2022,2024 T-Systems International GmbH
# Copyright (c) 2022,2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

name: Lint and Test Chart

on:
  push:
    paths:
      - 'charts/**'
    branches: [main]
  pull_request:
    paths:
      - 'charts/**'
  workflow_dispatch:
    inputs:
      node_image:
        description: 'kindest/node image for k8s kind cluster'
        # k8s version from 3.1 release
        default: 'kindest/node:v1.27.13'
        required: false
        type: string
      upgrade_from:
        description: 'SD Factory chart version to upgrade from'
        # SD Factory version from 24.03 release
        default: '2.1.10'
        required: false
        type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v2
        with:
          version: v0.19.0
          node_image: ${{ github.event.inputs.node_image || 'kindest/node:v1.27.13' }}
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kind-registry:5000/sdfactory:testing
                
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.10.3

      # Setup python as a prerequisite for chart linting 
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "CHART_CHANGED=true" >> $GITHUB_ENV
          fi
      # run chart linting 
      - name: Run chart-testing (lint)
        run: ct lint --charts charts/sdfactory --config charts/chart-testing-config.yaml


      # install the chart to the kind cluster and run helm test
      # define charts to test with the --charts parameter
      - name: Run chart-testing (install)
        run: ct install --charts charts/sdfactory --config charts/chart-testing-config.yaml --helm-extra-set-args "--set=image.tag=testing --set=image.repository=kind-registry:5000/sdfactory"
        if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'
        # Upgrade the released chart version with the locally available chart
        # default value for event_name != workflow_dispatch
      - name: Run helm upgrade
        run: |
          helm repo add tractusx https://eclipse-tractusx.github.io/charts/dev
          helm install sdf tractusx/sdfactory --version ${{ github.event.inputs.upgrade_from || '2.1.10' }}
          helm upgrade sdf charts/sdfactory
        if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'
